import React, { Component } from 'react';

class Contact extends Component {
  render(){
    return(
      <div className="contact">
        This is my Contact page
        <p>Cupcake ipsum dolor sit amet sweet. Marzipan I love wafer gingerbread bear claw. Macaroon liquorice jelly-o. Gingerbread cake I love caramels. Marshmallow caramels liquorice dragée toffee chocolate marshmallow. Cake candy muffin liquorice halvah. Chupa chups wafer caramels pudding jujubes cake bear claw. Toffee sweet dessert gummi bears pastry I love dessert halvah. Cupcake tootsie roll liquorice I love. Candy canes cake muffin biscuit ice cream liquorice I love marzipan brownie. Gingerbread pastry pastry tootsie roll liquorice cheesecake gummies. Pastry brownie lollipop fruitcake I love oat cake caramels. I love jelly I love I love gummies oat cake toffee candy canes halvah.</p>
        <p>Dessert sugar plum fruitcake jujubes cheesecake. Powder biscuit dragée sweet danish topping. Dragée oat cake sweet roll gummi bears. Dragée cheesecake cheesecake gummi bears fruitcake marshmallow pie brownie brownie. Powder bonbon chocolate bar soufflé croissant. Muffin powder jujubes pie icing. Jujubes caramels lollipop powder tootsie roll sweet. I love bonbon sweet caramels. Soufflé cotton candy pie cake. Bear claw sesame snaps cupcake fruitcake candy tiramisu. I love muffin macaroon biscuit cookie muffin. Powder I love oat cake. Croissant tart soufflé caramels gummies.</p>
        <p>Halvah sweet topping sesame snaps. Marshmallow cake I love icing. Gummies donut chocolate chocolate cake chocolate cake apple pie croissant. Cotton candy brownie caramels chocolate cake gummi bears chocolate bar. Bear claw gingerbread macaroon gingerbread muffin fruitcake liquorice biscuit candy canes. Pie cupcake donut ice cream icing macaroon tiramisu chocolate bar. Ice cream cupcake marshmallow powder cotton candy halvah. Gingerbread gingerbread gummi bears tiramisu. Dragée danish apple pie wafer biscuit I love chocolate. I love carrot cake jelly-o chocolate bar dessert pudding apple pie I love. Biscuit I love cake I love gummies tootsie roll biscuit jelly. Tootsie roll I love wafer bear claw cake fruitcake.</p>
        <p>Marshmallow carrot cake I love candy tiramisu pie powder. Sesame snaps bear claw oat cake caramels sweet donut I love gummi bears sweet roll. Donut chocolate lemon drops. Chocolate bar soufflé marshmallow gummi bears. Carrot cake cake cotton candy jelly beans cupcake. Tart soufflé toffee apple pie halvah gummies. I love bonbon chocolate cake oat cake sugar plum chocolate cake. Oat cake sweet roll cupcake. Caramels donut bear claw sugar plum cheesecake marshmallow sweet candy. Bear claw I love I love marshmallow cotton candy gummi bears oat cake. Danish halvah powder danish I love jelly beans cake soufflé bonbon. Topping cheesecake jelly beans chocolate cake chupa chups tootsie roll cotton candy oat cake. Tiramisu marzipan croissant topping oat cake gingerbread.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Cupcake ipsum dolor sit amet sweet. Marzipan I love wafer gingerbread bear claw. Macaroon liquorice jelly-o. Gingerbread cake I love caramels. Marshmallow caramels liquorice dragée toffee chocolate marshmallow. Cake candy muffin liquorice halvah. Chupa chups wafer caramels pudding jujubes cake bear claw. Toffee sweet dessert gummi bears pastry I love dessert halvah. Cupcake tootsie roll liquorice I love. Candy canes cake muffin biscuit ice cream liquorice I love marzipan brownie. Gingerbread pastry pastry tootsie roll liquorice cheesecake gummies. Pastry brownie lollipop fruitcake I love oat cake caramels. I love jelly I love I love gummies oat cake toffee candy canes halvah.</p>
        <p>Dessert sugar plum fruitcake jujubes cheesecake. Powder biscuit dragée sweet danish topping. Dragée oat cake sweet roll gummi bears. Dragée cheesecake cheesecake gummi bears fruitcake marshmallow pie brownie brownie. Powder bonbon chocolate bar soufflé croissant. Muffin powder jujubes pie icing. Jujubes caramels lollipop powder tootsie roll sweet. I love bonbon sweet caramels. Soufflé cotton candy pie cake. Bear claw sesame snaps cupcake fruitcake candy tiramisu. I love muffin macaroon biscuit cookie muffin. Powder I love oat cake. Croissant tart soufflé caramels gummies.</p>
        <p>Halvah sweet topping sesame snaps. Marshmallow cake I love icing. Gummies donut chocolate chocolate cake chocolate cake apple pie croissant. Cotton candy brownie caramels chocolate cake gummi bears chocolate bar. Bear claw gingerbread macaroon gingerbread muffin fruitcake liquorice biscuit candy canes. Pie cupcake donut ice cream icing macaroon tiramisu chocolate bar. Ice cream cupcake marshmallow powder cotton candy halvah. Gingerbread gingerbread gummi bears tiramisu. Dragée danish apple pie wafer biscuit I love chocolate. I love carrot cake jelly-o chocolate bar dessert pudding apple pie I love. Biscuit I love cake I love gummies tootsie roll biscuit jelly. Tootsie roll I love wafer bear claw cake fruitcake.</p>
        <p>Marshmallow carrot cake I love candy tiramisu pie powder. Sesame snaps bear claw oat cake caramels sweet donut I love gummi bears sweet roll. Donut chocolate lemon drops. Chocolate bar soufflé marshmallow gummi bears. Carrot cake cake cotton candy jelly beans cupcake. Tart soufflé toffee apple pie halvah gummies. I love bonbon chocolate cake oat cake sugar plum chocolate cake. Oat cake sweet roll cupcake. Caramels donut bear claw sugar plum cheesecake marshmallow sweet candy. Bear claw I love I love marshmallow cotton candy gummi bears oat cake. Danish halvah powder danish I love jelly beans cake soufflé bonbon. Topping cheesecake jelly beans chocolate cake chupa chups tootsie roll cotton candy oat cake. Tiramisu marzipan croissant topping oat cake gingerbread.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
        <p>Powder dessert I love I love bear claw cake tiramisu dessert. Caramels halvah carrot cake sweet roll biscuit cake. Sesame snaps jelly beans lollipop soufflé I love pie jelly beans. Cake cake cake liquorice pastry danish. Ice cream wafer topping sweet I love jujubes chupa chups. Jelly chocolate danish pudding lemon drops. Cupcake jujubes I love oat cake powder icing I love I love bear claw. Chupa chups pudding topping. Lemon drops cake lollipop brownie I love cotton candy I love. Cookie cake carrot cake. Tiramisu dragée fruitcake tootsie roll chocolate bar pudding. Candy jelly beans cake.</p>
      </div>
      )
  }
}

export default Contact;
